/**
 * Educational content for MatterGen and MatterSim info modals.
 * Condensed, informative sections combining overview and technical details.
 */

export interface InfoSection {
  heading: string
  content: string
}

export const mattergenInfo: InfoSection[] = [
  {
    heading: 'Overview',
    content:
      'MatterGen is a generative AI model that designs novel inorganic materials with targeted properties. Unlike traditional screening methods, it creates entirely new crystal structures using diffusion-based deep learning—jointly predicting atomic positions, element types, and lattice parameters.',
  },
  {
    heading: 'Property-Guided Generation',
    content:
      'Specify desired properties like bulk modulus, band gap, or magnetic density, and MatterGen generates candidate structures optimized for those targets. Different fine-tuned checkpoints handle different property combinations.',
  },
  {
    heading: 'Performance',
    content:
      'Trained on 600,000+ stable structures from the Materials Project and Alexandria databases. Achieves 38.6% rate of generating structures that are simultaneously stable, novel, and unique. Published in Nature (2025).',
  },
]

export const mattersimInfo: InfoSection[] = [
  {
    heading: 'Overview',
    content:
      'MatterSim is a universal machine learning force field that predicts material properties at near first-principles accuracy, but orders of magnitude faster than traditional DFT calculations. It evaluates structures across temperatures from 0–5000K and pressures up to 1000 GPa.',
  },
  {
    heading: 'Stability Evaluation',
    content:
      'Computes energy above the convex hull—a key metric for synthesis viability. Structures with energy above hull < 0.1 eV/atom are considered thermodynamically stable. Upload CIF files or transfer structures from MatterGen for evaluation.',
  },
  {
    heading: 'Why It Matters',
    content:
      'Traditional DFT calculations take hours or days per structure. MatterSim provides comparable accuracy in seconds, enabling rapid screening of thousands of candidates generated by MatterGen.',
  },
]
