/**
 * Cached demo outputs for golden-prefix examples.
 * Used for instant results when the live endpoint is slow or for booth demos.
 * These are real outputs from Dayhoff, not fabricated.
 * Label clearly as "Demo output" when shown from cache.
 */
import type { GenerationResponse } from './types'

export const DEMO_WORKFLOWS = [
  {
    key: 'cas9',
    label: 'Complete Cas9 prefix',
    prompt: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSG',
    model: '170m-UR50-BRn',
  },
  {
    key: 'insulin',
    label: 'Complete insulin prefix',
    prompt: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT',
    model: '170m-UR50-BRn',
  },
  {
    key: 'dnapol',
    label: 'Complete DNA polymerase prefix',
    prompt: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHK',
    model: '170m-UR50-BRn',
  },
  {
    key: 'spike',
    label: 'Spike protein variants',
    prompt: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFF',
    model: '170m-UR50-BRn',
  },
] as const

/**
 * Precomputed outputs from real Dayhoff model runs.
 * Keyed as `${model}::${prompt}` so each model variant gets its own cached result.
 * All 16 entries (4 prompts x 4 models) captured against dayhoff-score:v7.
 * Temperature 1.0, min_p 0.05, max_length 512, num_sequences 3.
 */
const PRECOMPUTED: Record<string, GenerationResponse> = {
  // -- cas9 x 170m-UR50-BRn --
  '170m-UR50-BRn::MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSG': {
    success: true,
    sequences: [
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGRITSNLASRIEEDPTRKKSDKVGVYDHRMNVLNNRKGYKDIDIFLKNFLPNKHGFVRVYHILEKALDKGEPVEFVGKKYKFELPILNKKLNSFKEKLFGKYRMQVHFLYLGQYLLNTILGAYILTNMVDSARSLLKIIDKNDRKRIKSAIKENNINEEQFESFIINNKELVNIQELKDGLLKDQSMLRLNATDKNNKNGYYESKQQLLNLNIQKLKEYLLETGLLNKLYIYEIYQKFIIENTVEEIVDNFETYLKNEFSNLRIIGPKSKLKNFNLKLPDDILLLSFTFALGLLNEVLSIINSYEKTQKKDKLKSLKVEDENGKKEIFVQKDEIEYIYSNYAKLNQFNVELTNTIISRLFPYLGDDKINEIINQIKLIRLSIEDRKPKSINTLNSFLHKLVKDEETIELEKLKEFLISNNNSNRDYNRELLLILLGILTSKYINEQNLKTTIEKINKNSNIRHLRDKIEKTYIISKLAESFSVSSKEDKEEDIKEVKSIESKIVNIIKEKKDE',
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGDRKDQRSSLRRLMRLFLQRHILKQFFLQEKENSNPLLLHQLNLLGDHKIQRDEIFLSAKKHLVESVIRTKFYFCLRSGILNEYNINLPEDISHAIGFVLHQMAESNRNSNANPVDLDFISINEELIFKAFNKKDSAELQKLEKLANLQNSTSIAKRLSNEIKNELGNDIADIFDAAKIFKEFKSLKNMFDTFKTLKNAISTVYYANPQVNSGELYDYIFNKIKELIKKPFYLQNKAFKLSIKKDASKYVNTVNHAFNISSKEKAELIAKYELEFFKNKINNNEPIEKDKLKDWKLNDCARELDFFDQITSEFNLANNGLVDSSLAKIFLQLKEKIIEPQRKKATQRLNAINRPVGHAEVSLSTKVQITKNRVEKMDENFSDNRDIFQEEISRWLRELTSEYSNDDINPAEFLNGNSVKSGLFGRINYVEKDAEFIVNILETGLYTDLLKIQTKLEHSLRDVYANYLLGNFKQHKEKYEKAWNVFYYQYLSAIAKRKRKIFISPIVVEKLYKS',
    ],
    sequences_with_fitness: [
      { fitness_score: 60.6, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGRITSNLASRIEEDPTRKKSDKVGVYDHRMNVLNNRKGYKDIDIFLKNFLPNKHGFVRVYHILEKALDKGEPVEFVGKKYKFELPILNKKLNSFKEKLFGKYRMQVHFLYLGQYLLNTILGAYILTNMVDSARSLLKIIDKNDRKRIKSAIKENNINEEQFESFIINNKELVNIQELKDGLLKDQSMLRLNATDKNNKNGYYESKQQLLNLNIQKLKEYLLETGLLNKLYIYEIYQKFIIENTVEEIVDNFETYLKNEFSNLRIIGPKSKLKNFNLKLPDDILLLSFTFALGLLNEVLSIINSYEKTQKKDKLKSLKVEDENGKKEIFVQKDEIEYIYSNYAKLNQFNVELTNTIISRLFPYLGDDKINEIINQIKLIRLSIEDRKPKSINTLNSFLHKLVKDEETIELEKLKEFLISNNNSNRDYNRELLLILLGILTSKYINEQNLKTTIEKINKNSNIRHLRDKIEKTYIISKLAESFSVSSKEDKEEDIKEVKSIESKIVNIIKEKKDE' },
      { fitness_score: 57.6, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGDRKDQRSSLRRLMRLFLQRHILKQFFLQEKENSNPLLLHQLNLLGDHKIQRDEIFLSAKKHLVESVIRTKFYFCLRSGILNEYNINLPEDISHAIGFVLHQMAESNRNSNANPVDLDFISINEELIFKAFNKKDSAELQKLEKLANLQNSTSIAKRLSNEIKNELGNDIADIFDAAKIFKEFKSLKNMFDTFKTLKNAISTVYYANPQVNSGELYDYIFNKIKELIKKPFYLQNKAFKLSIKKDASKYVNTVNHAFNISSKEKAELIAKYELEFFKNKINNNEPIEKDKLKDWKLNDCARELDFFDQITSEFNLANNGLVDSSLAKIFLQLKEKIIEPQRKKATQRLNAINRPVGHAEVSLSTKVQITKNRVEKMDENFSDNRDIFQEEISRWLRELTSEYSNDDINPAEFLNGNSVKSGLFGRINYVEKDAEFIVNILETGLYTDLLKIQTKLEHSLRDVYANYLLGNFKQHKEKYEKAWNVFYYQYLSAIAKRKRKIFISPIVVEKLYKS' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 59.1, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '170m-UR50-BRn', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- cas9 x 3b-UR90 --
  '3b-UR90::MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSG': {
    success: true,
    sequences: [
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGQTAADRRLFRTARRRYERRKNRILYLNEIFSEEMSKVDPNFFQRLDDSFLIEDDKGESSNLFNGLLPEEKYHQRYPTIYHLRKSLIEANEKFDIREIYLAIHHIIKYRGHFLFNGAIENIRLSDLNINDFAKDFLDIYNSFENLFSISNDDKSILESFLDTSNLRSTNRAKILADILLEKPIDNSTKKKSLAEVLIGLKGNLALSFVDGSDLSDKEISIRFDEDDYDEKLEDVKEIIGEEYIEKLSLLQDIYSWKILNDILEGKSYLSLAKVNAYEEHQKDLKKLKKLVKSYIPQSFLSIFKGQSNKSSLAKNYLNYIDSKSVEKTIPKEEFYNEIKKILDKKEFLPKQRTKDNGVIPHQLHLKELQAILSNASKHYPFLAEKKEDGSLSYVDKIKSLLTFRIPYYVGPLNNHSKHDWFARRTNVEITPWNFEEVVDKDQSAEKFIERMTNKCTYLPDEKVLPKNSLLYQKFTVLNELNNIKINGQPLSIEIKQKLFNELFLKKKKITRKQL',
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAAETRLFRSARRRLARRKSRILALQSIFVDEISKIDENFYPRLKESNLFPADPEKEKNANADYPLFKDANSNPDKELPYLLRADLLHSKINKDELAWLLRHIIQKRGHFLYDDPANKGASSAVKLTTDGFDEAYEKLNEALTENHKVNFEVKLKSDLDNNTKKKNRENEFKYSINLQRETAGRELELALKYRLDLQGEEKFSQLFGKDGKLKLDFSEFKQKDLDFETDTYEEEINELLGNLASLRATASAKAAMLLTIINHYLPVDKIKNEEYTANKVNLAENHLKLNERISRTKKAFYGKFIQADDKGKKIPLYENEDNKFYKQINEDKFFSLMKDKISKLSNQDSEQFFQMKKGGEYLPRQLQSENSLIPYQVHRYELEKILENQSKYYPFLKEGVAADSLTQAIKFSHYYGQHKTASNGAIPNQLHQYELDKIISNQGEYYPFLTENERNTIINKMTQNASFLPFLKKNKEGTLPYGAYSVDHLVPLSRSKDNSQWNLVACLPEENQ',
    ],
    sequences_with_fitness: [
      { fitness_score: 81.3, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGQTAADRRLFRTARRRYERRKNRILYLNEIFSEEMSKVDPNFFQRLDDSFLIEDDKGESSNLFNGLLPEEKYHQRYPTIYHLRKSLIEANEKFDIREIYLAIHHIIKYRGHFLFNGAIENIRLSDLNINDFAKDFLDIYNSFENLFSISNDDKSILESFLDTSNLRSTNRAKILADILLEKPIDNSTKKKSLAEVLIGLKGNLALSFVDGSDLSDKEISIRFDEDDYDEKLEDVKEIIGEEYIEKLSLLQDIYSWKILNDILEGKSYLSLAKVNAYEEHQKDLKKLKKLVKSYIPQSFLSIFKGQSNKSSLAKNYLNYIDSKSVEKTIPKEEFYNEIKKILDKKEFLPKQRTKDNGVIPHQLHLKELQAILSNASKHYPFLAEKKEDGSLSYVDKIKSLLTFRIPYYVGPLNNHSKHDWFARRTNVEITPWNFEEVVDKDQSAEKFIERMTNKCTYLPDEKVLPKNSLLYQKFTVLNELNNIKINGQPLSIEIKQKLFNELFLKKKKITRKQL' },
      { fitness_score: 70.0, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAAETRLFRSARRRLARRKSRILALQSIFVDEISKIDENFYPRLKESNLFPADPEKEKNANADYPLFKDANSNPDKELPYLLRADLLHSKINKDELAWLLRHIIQKRGHFLYDDPANKGASSAVKLTTDGFDEAYEKLNEALTENHKVNFEVKLKSDLDNNTKKKNRENEFKYSINLQRETAGRELELALKYRLDLQGEEKFSQLFGKDGKLKLDFSEFKQKDLDFETDTYEEEINELLGNLASLRATASAKAAMLLTIINHYLPVDKIKNEEYTANKVNLAENHLKLNERISRTKKAFYGKFIQADDKGKKIPLYENEDNKFYKQINEDKFFSLMKDKISKLSNQDSEQFFQMKKGGEYLPRQLQSENSLIPYQVHRYELEKILENQSKYYPFLKEGVAADSLTQAIKFSHYYGQHKTASNGAIPNQLHQYELDKIISNQGEYYPFLTENERNTIINKMTQNASFLPFLKKNKEGTLPYGAYSVDHLVPLSRSKDNSQWNLVACLPEENQ' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 75.7, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-UR90', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- cas9 x 3b-GR-HM-c --
  '3b-GR-HM-c::MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSG': {
    success: true,
    sequences: [
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEANRLKRTNRRRYSRRKRRLLYLQQLFEEEIKKVDPNFFQRLNESRLSFDDKNKKTGTWVRTLQQYSDSFPNKDFFHDAYPTLKKKELYFPTFKLDNTQEAFYPRLKARGFYLNEKVCYQEIRKWELQEEDFTKTNHKKEPLITIQEEYELIKSLFNKKEFYKVPIYQRDYAWDKENWEELWDDITFKAIDSRFEKDRGSIQSYFGTIIITGDGKNKNYEVIDGQQRLTSLFILLSVLRDQIRIKPQCLNELKDEISNDSFNSKPKLIFKNRKEFEYYRDNLLLLSEFVDYEHEFFVDLLYSEQMRMKYYLIDEMLEKLNNLANEALLTQEELFSNIEKLNNFFKDVKDINVDHEKRIFESLNRGGLPLNPFEIRKSVYSDIISKALSRKFEEYWGDLVESKRGGKSLMGSFISSRNEKDEESYKLADSDYFVAVLYFYSQETIKGKLTFEKDKERIFKRVDVENGYVTSETLELWSLLYVLVNEKVGFEAFSIQLNEMNTISYALQNS',
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEANRIKRTARRRYTRRKHRLQFLQQLFAEEIAKVDDTFFQRLKESKLTPDDKKAKGKLPYHDIDSNYFTKKEFHQKYPTLYHLRKELIDETEKYDVRLVYLAMHYFLKNNPKMLLKQTPAEKHVSYQFDKIEDYYAMIENYQRIAFHIIKQTAKDKDGKINVEKPVLRNFKKLINNLKPEEIESLINDPTVVDNDDSYWLALKNICLIQDADIDKTYTTIDRDDLKLTKRKNIVFGNITKDYLYGKDNLNTNSSEWDDKAFIDRKRKVSTYGEIYSDPKNIKERYPHIYDIIKKIKKNYITPEEQQKIKNLFDNEYEIQNLWETLQQAKDNCNSLHKLTEEEKELLKRTIYVYEGTDTYVSSKYIVDLINSNKTRNNFLNLKQIIKEDAPRLINKNFKNKTYEQDLSRAINNIAQYNRKFGKKLDEWLELYPKVIEIDSISDFRDAEYRADKQGLFNDHRVVYNMHRPHTGINNILPPMILGEDENSINTNKKYFYGSKMVMKSLPNNK',
    ],
    sequences_with_fitness: [
      { fitness_score: 68.1, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEANRLKRTNRRRYSRRKRRLLYLQQLFEEEIKKVDPNFFQRLNESRLSFDDKNKKTGTWVRTLQQYSDSFPNKDFFHDAYPTLKKKELYFPTFKLDNTQEAFYPRLKARGFYLNEKVCYQEIRKWELQEEDFTKTNHKKEPLITIQEEYELIKSLFNKKEFYKVPIYQRDYAWDKENWEELWDDITFKAIDSRFEKDRGSIQSYFGTIIITGDGKNKNYEVIDGQQRLTSLFILLSVLRDQIRIKPQCLNELKDEISNDSFNSKPKLIFKNRKEFEYYRDNLLLLSEFVDYEHEFFVDLLYSEQMRMKYYLIDEMLEKLNNLANEALLTQEELFSNIEKLNNFFKDVKDINVDHEKRIFESLNRGGLPLNPFEIRKSVYSDIISKALSRKFEEYWGDLVESKRGGKSLMGSFISSRNEKDEESYKLADSDYFVAVLYFYSQETIKGKLTFEKDKERIFKRVDVENGYVTSETLELWSLLYVLVNEKVGFEAFSIQLNEMNTISYALQNS' },
      { fitness_score: 66.7, length: 568, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEANRIKRTARRRYTRRKHRLQFLQQLFAEEIAKVDDTFFQRLKESKLTPDDKKAKGKLPYHDIDSNYFTKKEFHQKYPTLYHLRKELIDETEKYDVRLVYLAMHYFLKNNPKMLLKQTPAEKHVSYQFDKIEDYYAMIENYQRIAFHIIKQTAKDKDGKINVEKPVLRNFKKLINNLKPEEIESLINDPTVVDNDDSYWLALKNICLIQDADIDKTYTTIDRDDLKLTKRKNIVFGNITKDYLYGKDNLNTNSSEWDDKAFIDRKRKVSTYGEIYSDPKNIKERYPHIYDIIKKIKKNYITPEEQQKIKNLFDNEYEIQNLWETLQQAKDNCNSLHKLTEEEKELLKRTIYVYEGTDTYVSSKYIVDLINSNKTRNNFLNLKQIIKEDAPRLINKNFKNKTYEQDLSRAINNIAQYNRKFGKKLDEWLELYPKVIEIDSISDFRDAEYRADKQGLFNDHRVVYNMHRPHTGINNILPPMILGEDENSINTNKKYFYGSKMVMKSLPNNK' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 67.4, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-GR-HM-c', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- cas9 x 3b-GR-HM --
  '3b-GR-HM::MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSG': {
    success: true,
    sequences: [
      'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAETRRLKRTARRRYTRRKNRIRYLQEIFAEEMEKVDDEFYRHLERNPIHDTKEKFLAYKEDLDREVENPKYQFFEHDSLEETDQIRLKRQELANNSWAAYTYSDTKGNRKYLGNNELNGKPIEKDEISDHDFPLLRFADVLLMYAECLNETGDNAGAVKYINMVRERAQKGTDGINNVDKALFREELLFERGLEFAGEGLRRFDLIRTGKLPEAIKNITYKRAGEGYLQTWPYYNIEDEYMPNWNQ',
    ],
    sequences_with_fitness: [
      { fitness_score: 79.3, length: 304, sequence: 'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAETRRLKRTARRRYTRRKNRIRYLQEIFAEEMEKVDDEFYRHLERNPIHDTKEKFLAYKEDLDREVENPKYQFFEHDSLEETDQIRLKRQELANNSWAAYTYSDTKGNRKYLGNNELNGKPIEKDEISDHDFPLLRFADVLLMYAECLNETGDNAGAVKYINMVRERAQKGTDGINNVDKALFREELLFERGLEFAGEGLRRFDLIRTGKLPEAIKNITYKRAGEGYLQTWPYYNIEDEYMPNWNQ' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 79.3, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '3b-GR-HM', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
  // -- insulin x 170m-UR50-BRn --
  '170m-UR50-BRn::MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT': {
    success: true,
    sequences: [
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTDYGTCGNNEYHKCCRGLPSHKYHRSRFMQETAQFSYSLDTNNFCLTGSTEGQKHSWIYRNFKRNHDFDKYLADNNNPDTFSMSEPCPFIPGQCKKLLLKNRTRINMRIECDSLNAHCGSISTPHECQALGRDKLHIFNKLDSSAAGCNEINSKTSELWEACTDPQALANLKMVNDILSGCNESPWTCATKWHLAGLVKKKTTNDYPSLGSEFLVCEWNLQELEECVKKPVAAQKEYDAWLSVVSCNTFEVYKEKQQNSRTVDTGFKDTNYSSYSPINIPRYVCLTLAVLLAGILIYRAVKKASKKFGHKTKKRQLERPIKSLLDADLNATTGSSMSNSGMQSLLEMKPVTFLSTSHPCPSYAQVPNPQRIPTIDQYSKEESPDQGKPVEEKRGQSHEPLVRDTILYYSQHVAQVQPSHDPSLNIGQHNNEVRHQGMNYPATVRSHEPLVRDTILYYSQHVAQVQPSHDPSLNIGQHNNEVRHQGMNYPATVRSHEPLVRDTILYYSQHVAQV',
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTDGTYGPGVAPGRSCLHWAERARREGEGGGRGSVWGNASTAPSDVLGPGQPLHLELRGSDGLMEFVYCTGAAGETLACPADGIPRAEAEVVDATQLLRLDGAAPHQNLAAMPATYRCSDPRAAGPRPARQPEDSAEMTSAGILLPVSTLSDTSLTSLVFGQMLDKTMSGERHIQPGSLEYDGFHGLQRIPATDSSLVWSAGCGGAALILFEACWPGLCRMDCAEEEGNAVVIEQRGERKALKEVSELGSVPVKFEQELVEVQVIKTRINVGGTVDILVESVPQGLGWAAVSRRLSVFSAAQAVAAGVARLVAEVGLVRPPDARPRWCYSLHCGHSVARRAWQWHGFSELALFDASQELQVIQKALFSHEKKCFTVASPRCGAPSAVVVCRGPAKEPLECAVPPSGCAAGPLFRDLCRASPCVEGRECVFHSTPSSPSAVCSCPPGFGGLRCEHQKEDCYRAEGQCHPGFHCLRADHVGLRCVHPATKLIATLLLCAVLVALPVLLVRKQLTQG',
    ],
    sequences_with_fitness: [
      { fitness_score: 61.2, length: 566, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTDYGTCGNNEYHKCCRGLPSHKYHRSRFMQETAQFSYSLDTNNFCLTGSTEGQKHSWIYRNFKRNHDFDKYLADNNNPDTFSMSEPCPFIPGQCKKLLLKNRTRINMRIECDSLNAHCGSISTPHECQALGRDKLHIFNKLDSSAAGCNEINSKTSELWEACTDPQALANLKMVNDILSGCNESPWTCATKWHLAGLVKKKTTNDYPSLGSEFLVCEWNLQELEECVKKPVAAQKEYDAWLSVVSCNTFEVYKEKQQNSRTVDTGFKDTNYSSYSPINIPRYVCLTLAVLLAGILIYRAVKKASKKFGHKTKKRQLERPIKSLLDADLNATTGSSMSNSGMQSLLEMKPVTFLSTSHPCPSYAQVPNPQRIPTIDQYSKEESPDQGKPVEEKRGQSHEPLVRDTILYYSQHVAQVQPSHDPSLNIGQHNNEVRHQGMNYPATVRSHEPLVRDTILYYSQHVAQVQPSHDPSLNIGQHNNEVRHQGMNYPATVRSHEPLVRDTILYYSQHVAQV' },
      { fitness_score: 57.4, length: 566, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTDGTYGPGVAPGRSCLHWAERARREGEGGGRGSVWGNASTAPSDVLGPGQPLHLELRGSDGLMEFVYCTGAAGETLACPADGIPRAEAEVVDATQLLRLDGAAPHQNLAAMPATYRCSDPRAAGPRPARQPEDSAEMTSAGILLPVSTLSDTSLTSLVFGQMLDKTMSGERHIQPGSLEYDGFHGLQRIPATDSSLVWSAGCGGAALILFEACWPGLCRMDCAEEEGNAVVIEQRGERKALKEVSELGSVPVKFEQELVEVQVIKTRINVGGTVDILVESVPQGLGWAAVSRRLSVFSAAQAVAAGVARLVAEVGLVRPPDARPRWCYSLHCGHSVARRAWQWHGFSELALFDASQELQVIQKALFSHEKKCFTVASPRCGAPSAVVVCRGPAKEPLECAVPPSGCAAGPLFRDLCRASPCVEGRECVFHSTPSSPSAVCSCPPGFGGLRCEHQKEDCYRAEGQCHPGFHCLRADHVGLRCVHPATKLIATLLLCAVLVALPVLLVRKQLTQG' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 59.3, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '170m-UR50-BRn', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- insulin x 3b-UR90 --
  '3b-UR90::MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT': {
    success: true,
    sequences: [
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRRGVEDPQVSVLSPLQMSPEVEELGATETDPNRLARVQPLLIANQRKRGIVEQCCHTACDIYNLENYCNRQ',
    ],
    sequences_with_fitness: [
      { fitness_score: 82.2, length: 125, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRRGVEDPQVSVLSPLQMSPEVEELGATETDPNRLARVQPLLIANQRKRGIVEQCCHTACDIYNLENYCNRQ' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 82.2, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '3b-UR90', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
  // -- insulin x 3b-GR-HM-c --
  '3b-GR-HM-c::MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT': {
    success: true,
    sequences: [
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTPDSRGYSGRFRGRLRSFAGVVEECCLRACSLSELELYCAPAAPKERKHSPRAAGRPSLAPRPAADWQPLPAPVTLPAAAGGGGGGAVAAGGRPRRARRLLSTRRLPPLPPRLLAGAQEPPPPPRHLPLGGSSLRGLGNAAPPRGCVPGYVPVAPAGAPLPGALASRRRLGYARTAV',
    ],
    sequences_with_fitness: [
      { fitness_score: 70.8, length: 230, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTPDSRGYSGRFRGRLRSFAGVVEECCLRACSLSELELYCAPAAPKERKHSPRAAGRPSLAPRPAADWQPLPAPVTLPAAAGGGGGGAVAAGGRPRRARRLLSTRRLPPLPPRLLAGAQEPPPPPRHLPLGGSSLRGLGNAAPPRGCVPGYVPVAPAGAPLPGALASRRRLGYARTAV' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 70.8, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '3b-GR-HM-c', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
  // -- insulin x 3b-GR-HM --
  '3b-GR-HM::MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKT': {
    success: true,
    sequences: [
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTLQTKRRPFEYWYLQMTQPEFWNPGAWNGCNAEKGLSCEVELTWTPFLPPATLNRVDQEALLNKWIRGPPSSTSSSSSGGTSSSGGGAASGSSTAGGSSGGGGSAAAGGSTSGAGGGAASSAASAASSAGSSGSAGAASAAAAAGGGSTSSSAAAGGTAGGSTAAGGSTAAGGSTAAGGSTAAGGSASSASAAGGTTGGSTAAGGTSAASGTAAASGTAAAGGSTTAGGSTSAASGTAAAASSSTAAGGSTTAGGSTSAASGTAAASGTAAAASSSTAAGGSTTAGGSTSAASGTAAASGTAAASSTAAAGGSTSAASGTAAASSTAAASSTAAGGSTTAASSTAASSTTASGGSTTAASGTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTASGGSTTAASSTAASSTTASGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTA',
      'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTPSVIWGNYIYLARKAMPDRKPITFSSAQDLNDFFVNHVLKNYNARKTFSTQVAHWFIGVPANEVKPKEVNEERMKFILSQNTKYALLYSMKELKCAHEQHICCVCLAEYPSRTKCVFFINSGIAFTFCFVHIIVPEAVLENRKDHGDLIPPLACIPPHLSPVLAVRQTQISMSKGALFECMYPFGVQLHQVVCPWWTLIILGMVLSATGFGFVSNYVLIVPLVGGWLASGLLGCLAAVLELMFAWRVKHSILASSMVLVVSVAHFSYALYWGVGLSSGMVLFDTPFVTFAIFAQMACAKLMLRRGRSERLTFYDVLKQKARTASVHGVYLALAPYLSNGIYWSDPVAIMKNIPFVVLDGLLIVGPPVVFLYVDVDYVFYAPIPWPTQGLEFPRWARCQEGEGWRGVGLHSNSHTGSVPWTAGSSSSMAHSSSTMGPSGVGCDSPDSGKAVAKAYVKGEEGQVLGLWLRSEEEGRSRNETAAEEKRLRDSGEREERRGAEDGGDGRDGSQRVE',
    ],
    sequences_with_fitness: [
      { fitness_score: 85.9, length: 566, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTLQTKRRPFEYWYLQMTQPEFWNPGAWNGCNAEKGLSCEVELTWTPFLPPATLNRVDQEALLNKWIRGPPSSTSSSSSGGTSSSGGGAASGSSTAGGSSGGGGSAAAGGSTSGAGGGAASSAASAASSAGSSGSAGAASAAAAAGGGSTSSSAAAGGTAGGSTAAGGSTAAGGSTAAGGSTAAGGSASSASAAGGTTGGSTAAGGTSAASGTAAASGTAAAGGSTTAGGSTSAASGTAAAASSSTAAGGSTTAGGSTSAASGTAAASGTAAAASSSTAAGGSTTAGGSTSAASGTAAASGTAAASSTAAAGGSTSAASGTAAASSTAAASSTAAGGSTTAASSTAASSTTASGGSTTAASGTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTASGGSTTAASSTAASSTTASGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTAAGGSTTAASSTAASSTTA' },
      { fitness_score: 53.5, length: 566, sequence: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTPSVIWGNYIYLARKAMPDRKPITFSSAQDLNDFFVNHVLKNYNARKTFSTQVAHWFIGVPANEVKPKEVNEERMKFILSQNTKYALLYSMKELKCAHEQHICCVCLAEYPSRTKCVFFINSGIAFTFCFVHIIVPEAVLENRKDHGDLIPPLACIPPHLSPVLAVRQTQISMSKGALFECMYPFGVQLHQVVCPWWTLIILGMVLSATGFGFVSNYVLIVPLVGGWLASGLLGCLAAVLELMFAWRVKHSILASSMVLVVSVAHFSYALYWGVGLSSGMVLFDTPFVTFAIFAQMACAKLMLRRGRSERLTFYDVLKQKARTASVHGVYLALAPYLSNGIYWSDPVAIMKNIPFVVLDGLLIVGPPVVFLYVDVDYVFYAPIPWPTQGLEFPRWARCQEGEGWRGVGLHSNSHTGSVPWTAGSSSSMAHSSSTMGPSGVGCDSPDSGKAVAKAYVKGEEGQVLGLWLRSEEEGRSRNETAAEEKRLRDSGEREERRGAEDGGDGRDGSQRVE' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 69.7, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-GR-HM', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- dnapol x 170m-UR50-BRn --
  '170m-UR50-BRn::MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHK': {
    success: true,
    sequences: [
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYLTLGKAKFEQISETFNVSVEELRACIDELNVDKDKFNETIAILSKMMVGVTSSVNMSTGNRLFMVDEFRMKISVFKNALQEIIRDHYQRFIKDMTFLIMDFDGLNDWVTSRDRDVQLLREVKPIPDTVPPKLKANADYVYVDPPDYPVVVEKLSKTLVECCKLLRCYVIKPPISKRKLRLEIKRNDILNGVQRTVEERKEFGEQFWQFLLNETQRAQQIRNVIINCGGKQFVLPSTPHPRTKFFKFGFRKSSAKGLRVLLLPNTGYDDSPSTDNLFDFKISETPFNDSDMEIDARSIKTTSPEKSIPSLFRHPDHGARLFPSNVFDFEALTEMIELYLREYIKRNKAFLTITNYQEVVETLASMMGYFTAAKIHIGRLNSNHDAHKEYHKKLSSLGVLPKSYERAKEIYEFKIIRMVCPDLDRSRINKIWMSQVSLKTRKKALYSLKVYKVELLHTFNEVNTRLCKPQKSNNNAEYNDDLYLVDDDDEDNNGSVFYEIKDDVTSLTGSNRL',
    ],
    sequences_with_fitness: [
      { fitness_score: 53.6, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYLTLGKAKFEQISETFNVSVEELRACIDELNVDKDKFNETIAILSKMMVGVTSSVNMSTGNRLFMVDEFRMKISVFKNALQEIIRDHYQRFIKDMTFLIMDFDGLNDWVTSRDRDVQLLREVKPIPDTVPPKLKANADYVYVDPPDYPVVVEKLSKTLVECCKLLRCYVIKPPISKRKLRLEIKRNDILNGVQRTVEERKEFGEQFWQFLLNETQRAQQIRNVIINCGGKQFVLPSTPHPRTKFFKFGFRKSSAKGLRVLLLPNTGYDDSPSTDNLFDFKISETPFNDSDMEIDARSIKTTSPEKSIPSLFRHPDHGARLFPSNVFDFEALTEMIELYLREYIKRNKAFLTITNYQEVVETLASMMGYFTAAKIHIGRLNSNHDAHKEYHKKLSSLGVLPKSYERAKEIYEFKIIRMVCPDLDRSRINKIWMSQVSLKTRKKALYSLKVYKVELLHTFNEVNTRLCKPQKSNNNAEYNDDLYLVDDDDEDNNGSVFYEIKDDVTSLTGSNRL' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 53.6, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '170m-UR50-BRn', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
  // -- dnapol x 3b-UR90 --
  '3b-UR90::MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHK': {
    success: true,
    sequences: [
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYNAVVSEMEKCHSLKATCTALGDVAGLCLTVNKKLVGIIASSCLEPGVKAKKWSSTAEPATSKNCVHGEDVIDKKDEKRLKEERLCLQTELSLLLQNKEAAASQCESLSSANKHLRSQLEGERQRLEESEMAVNHSKEELEQLRKENSSLLNVRLSLLQEISTKERELQLWQEVTTAVTSQPESTENLVQKLNILQDEKANLEIQLAKGEEQISDYVNQLIEAKAALDEKTREVELLRNSCNSRMNQMEEEQKVVIRNLSEKLKEQRKRLETEKKKSTEVEERLQAEQNLAAKLKEQNNYLTSCLEQVGNVNDDLKEQISEVSKAYEGMAKEWKEAKKLLEEERNKTLQSDKLLEKLELENKNLECQVTKLRQEMEKADGNQIARVDSLENSLQEYQERVHQLEHENNEFKTKDNHNVKLKAELTSVKEELESRTSRWNKAVESLNQADAARLTELEKKYQDLEEEKKKMRSRKLEALLLMQEAKALPEETEPQVHGELDSVSEVDSHSENS',
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYNAYVNKMNAQLKVLQAGGDNTAQLQPKKDKRETDLKTSLELWQKAEADLQDLQRKLDSIATENPQHVHRTALASSTPVTFHGAENSEGSTQLQLNGFTSSLEKFLEAAKVNSANPASSFKDSRKKEFFYLEQKRKRMDSQSSTEFQEARQKLQEEASQKAMEAEKRKRALQEARELKDKEEAELREKARHAQEEHRRKTTEAQKRKDESDTAYRKAVGTSRKAEEVRRVVQSEINGQIRKLESDQNRLQGALSAVAENEEKLKEAELSAGRYQGEADDRLSSLVSETESVKARLEKLKAEVAGTSDDLSVLEKELARTKQERDAVLSTIQKLKGRNEELQQEVLVLSHSLADQRRRRKQTEDGLRTREKRVEAMKVRFEVEARMAAAEGQKQKGQVEAQVRRYRNLEQQVRQASVQKEAQPAPFAAPGAVRSPPLQPKEQEETGDDFGVQGFRHNQQEDEAKGEPPPQVTQESSRTSSGSAPSTVELPVSFRPSKSSSPPRRPQQSIKSPM',
    ],
    sequences_with_fitness: [
      { fitness_score: 71.3, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYNAVVSEMEKCHSLKATCTALGDVAGLCLTVNKKLVGIIASSCLEPGVKAKKWSSTAEPATSKNCVHGEDVIDKKDEKRLKEERLCLQTELSLLLQNKEAAASQCESLSSANKHLRSQLEGERQRLEESEMAVNHSKEELEQLRKENSSLLNVRLSLLQEISTKERELQLWQEVTTAVTSQPESTENLVQKLNILQDEKANLEIQLAKGEEQISDYVNQLIEAKAALDEKTREVELLRNSCNSRMNQMEEEQKVVIRNLSEKLKEQRKRLETEKKKSTEVEERLQAEQNLAAKLKEQNNYLTSCLEQVGNVNDDLKEQISEVSKAYEGMAKEWKEAKKLLEEERNKTLQSDKLLEKLELENKNLECQVTKLRQEMEKADGNQIARVDSLENSLQEYQERVHQLEHENNEFKTKDNHNVKLKAELTSVKEELESRTSRWNKAVESLNQADAARLTELEKKYQDLEEEKKKMRSRKLEALLLMQEAKALPEETEPQVHGELDSVSEVDSHSENS' },
      { fitness_score: 67.3, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKYNAYVNKMNAQLKVLQAGGDNTAQLQPKKDKRETDLKTSLELWQKAEADLQDLQRKLDSIATENPQHVHRTALASSTPVTFHGAENSEGSTQLQLNGFTSSLEKFLEAAKVNSANPASSFKDSRKKEFFYLEQKRKRMDSQSSTEFQEARQKLQEEASQKAMEAEKRKRALQEARELKDKEEAELREKARHAQEEHRRKTTEAQKRKDESDTAYRKAVGTSRKAEEVRRVVQSEINGQIRKLESDQNRLQGALSAVAENEEKLKEAELSAGRYQGEADDRLSSLVSETESVKARLEKLKAEVAGTSDDLSVLEKELARTKQERDAVLSTIQKLKGRNEELQQEVLVLSHSLADQRRRRKQTEDGLRTREKRVEAMKVRFEVEARMAAAEGQKQKGQVEAQVRRYRNLEQQVRQASVQKEAQPAPFAAPGAVRSPPLQPKEQEETGDDFGVQGFRHNQQEDEAKGEPPPQVTQESSRTSSGSAPSTVELPVSFRPSKSSSPPRRPQQSIKSPM' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 69.3, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-UR90', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- dnapol x 3b-GR-HM-c --
  '3b-GR-HM-c::MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHK': {
    success: true,
    sequences: [
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKALEASLPAEIKRLQEQVGILSNKVVNLETSFKQETKQVVSELQKIRIGLNALTKRPDKQHDMMETLRKEVNELKGEKAELKKNISGLKNETIQIRSLLKDIKSQLRLQFGSNPYNVLRQEPGGENHVPESDSTEEDQSVSPDDSSPHRSETPDHTVSPDGSSPDQSDAPDETVSSDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHT',
    ],
    sequences_with_fitness: [
      { fitness_score: 87.3, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKALEASLPAEIKRLQEQVGILSNKVVNLETSFKQETKQVVSELQKIRIGLNALTKRPDKQHDMMETLRKEVNELKGEKAELKKNISGLKNETIQIRSLLKDIKSQLRLQFGSNPYNVLRQEPGGENHVPESDSTEEDQSVSPDDSSPHRSETPDHTVSPDGSSPDQSDAPDETVSSDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHTVSPDDSSSDQSETPDHTVSPDDSSSDQSETPDHTISPDGSSPHQSETPDHT' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 87.3, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '3b-GR-HM-c', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
  // -- dnapol x 3b-GR-HM --
  '3b-GR-HM::MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHK': {
    success: true,
    sequences: [
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKLDESEKSSESLEKVRVELSALISRSDDQVEKVERLSDEFESYLTKFKSRFKEQMSEIHKCEQETKEMKFEKSILIARLQVLDKDRQLEFSTNNIQLLTRLDEVQKEAESLQTDLDKEKSRQTRLLQEVEARSTNAQVKELQLLQSQIEEEKQQQDALLLEIKRLQGERKRFEESVKISQMKDDKENKFNNQFETLEAICHAEISQYESELMKLESEKAELGKFFSETTEETRNLKIELKGVRQAMEAKRRSDSELLISLEKSSSDNSDLSEKIELLQKTLANKRTDAEKNYLDLTRDYESSKVEKEKIETTLDAIVNKFGVVAEEVQKTKSKITSQLDLAGAELKEHNSKIVQLTTENGHLNEELANAQHLVKIKDEEISRMREKNQALQLDLAGAKEEISRLKDDNRSLAEDIRHLKKNAPVPASSTTPPHLPQNVASSDIKLEAEVDRLTRQNSALVEEADKTRDLLTTKDTEIDELKRELREAHLKILQQEAELESQERQSVVAVKPTQ',
      'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKFPPDNKIRKYKNVQIVAAILLAAQTAAHRAQEQQDVLLVNEMVTWHELTDKLQASIDSQSRETMIGLGKEIQALDTKAIDVTKEVKTIISSTKAFKSRGIAHFDNPPENSEEDQAEKGKKESKVPALQPHAIKEVAAQTKADNNTLYSLTSSIESEKRKLNRGIDTNEMDALVQGLKNTSGNISNDIKKIINDFEKEYPTNSQIKQQQTRAILNQTLMALNDSKVLFEKNAQIHHEELFADLKSLQEALISNHQLMSRSEHALNEAGFRAVEKTGKTKSLIDQSFSGLVLHQQVFKKNIGEHTDRVLTVVQDLSVKSEERLLVLKEKVNSLLAESFKRSEKRAAEKSEISYNIDKQLELVVNISKKIGDSNLTESEIQETAAAAEKLFNDTVVYIKGRAKESIRLQENLLNMLIDGFENVLTADLLTTLRRLASTTQEVYHQVFQRTADGIQKLETASTTHIKALSANFDERTDTITQQIDDFRKISETAMEELEMNHETKIKKIIDSIEGH',
    ],
    sequences_with_fitness: [
      { fitness_score: 62.5, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKLDESEKSSESLEKVRVELSALISRSDDQVEKVERLSDEFESYLTKFKSRFKEQMSEIHKCEQETKEMKFEKSILIARLQVLDKDRQLEFSTNNIQLLTRLDEVQKEAESLQTDLDKEKSRQTRLLQEVEARSTNAQVKELQLLQSQIEEEKQQQDALLLEIKRLQGERKRFEESVKISQMKDDKENKFNNQFETLEAICHAEISQYESELMKLESEKAELGKFFSETTEETRNLKIELKGVRQAMEAKRRSDSELLISLEKSSSDNSDLSEKIELLQKTLANKRTDAEKNYLDLTRDYESSKVEKEKIETTLDAIVNKFGVVAEEVQKTKSKITSQLDLAGAELKEHNSKIVQLTTENGHLNEELANAQHLVKIKDEEISRMREKNQALQLDLAGAKEEISRLKDDNRSLAEDIRHLKKNAPVPASSTTPPHLPQNVASSDIKLEAEVDRLTRQNSALVEEADKTRDLLTTKDTEIDELKRELREAHLKILQQEAELESQERQSVVAVKPTQ' },
      { fitness_score: 56.6, length: 547, sequence: 'MSKRKAPQETLNGGITDMLTELANFEKNVSQAIHKFPPDNKIRKYKNVQIVAAILLAAQTAAHRAQEQQDVLLVNEMVTWHELTDKLQASIDSQSRETMIGLGKEIQALDTKAIDVTKEVKTIISSTKAFKSRGIAHFDNPPENSEEDQAEKGKKESKVPALQPHAIKEVAAQTKADNNTLYSLTSSIESEKRKLNRGIDTNEMDALVQGLKNTSGNISNDIKKIINDFEKEYPTNSQIKQQQTRAILNQTLMALNDSKVLFEKNAQIHHEELFADLKSLQEALISNHQLMSRSEHALNEAGFRAVEKTGKTKSLIDQSFSGLVLHQQVFKKNIGEHTDRVLTVVQDLSVKSEERLLVLKEKVNSLLAESFKRSEKRAAEKSEISYNIDKQLELVVNISKKIGDSNLTESEIQETAAAAEKLFNDTVVYIKGRAKESIRLQENLLNMLIDGFENVLTADLLTTLRRLASTTQEVYHQVFQRTADGIQKLETASTTHIKALSANFDERTDTITQQIDDFRKISETAMEELEMNHETKIKKIIDSIEGH' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 59.5, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-GR-HM', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- spike x 170m-UR50-BRn --
  '170m-UR50-BRn::MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFF': {
    success: true,
    sequences: [
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFRDPRAEIVVFESNKKSRKKTCRYDIWEAQAKGTVGVTDAASGVMSPTTKGYQGILKFESRAIQNYSYYNYQVKSLKGSDKRFSLQCYAVLVPNKGYRHEPMWKVATGQGDLCTLQDNEIPGSAQSYDDKSQPGQSYASNAWASSPEIKLAAATFVPKLLVQSPAVLGHRSFVTIIGAPGSGKSTFIKHVFKDNGQPTTSVLATSRGLRDDLNAGDRRTGGQLVTALDFTPAEETPMEGLDVLSPRRTRCAHFCYPPNISFGGDESLLADCLDNPANVVGVIYDSSGFGNMYDLFIAQLCDDDSYNHMQAKKFVVSLVDPASLVQASEQHAARLNMRPLENTCTELNVNVQPALAAFLLGYAVSLVNTRGDVLAKLMCPAEKDMIPMSRFQPPPPSGVLLATVFSKHLHIMKVTVVSCSPVEPNDVYLSVLNQNYHAECKKNFPADSVAAAMRPGYHACMFTPATNPASPGCECTIIYNPSGELRAQVTHRAQTPGRSVLKTQISMLLLLPPA',
    ],
    sequences_with_fitness: [
      { fitness_score: 53.4, length: 571, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFRDPRAEIVVFESNKKSRKKTCRYDIWEAQAKGTVGVTDAASGVMSPTTKGYQGILKFESRAIQNYSYYNYQVKSLKGSDKRFSLQCYAVLVPNKGYRHEPMWKVATGQGDLCTLQDNEIPGSAQSYDDKSQPGQSYASNAWASSPEIKLAAATFVPKLLVQSPAVLGHRSFVTIIGAPGSGKSTFIKHVFKDNGQPTTSVLATSRGLRDDLNAGDRRTGGQLVTALDFTPAEETPMEGLDVLSPRRTRCAHFCYPPNISFGGDESLLADCLDNPANVVGVIYDSSGFGNMYDLFIAQLCDDDSYNHMQAKKFVVSLVDPASLVQASEQHAARLNMRPLENTCTELNVNVQPALAAFLLGYAVSLVNTRGDVLAKLMCPAEKDMIPMSRFQPPPPSGVLLATVFSKHLHIMKVTVVSCSPVEPNDVYLSVLNQNYHAECKKNFPADSVAAAMRPGYHACMFTPATNPASPGCECTIIYNPSGELRAQVTHRAQTPGRSVLKTQISMLLLLPPA' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 53.4, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '170m-UR50-BRn', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- spike x 3b-UR90 --
  '3b-UR90::MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFF': {
    success: true,
    sequences: [
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFDNPATYGNVSFGFWINVDHSTQKDDGVTFEIFPYSDDQLDAYTAQGTLSSLSLSFISSVDSHIVLEKQGLKVPGVVGLEIESFYWRFMFTVESQSSVDRYTLSFEKNPELFWEKWDTTLDRYMGQTGLSLGIPTIQSSLDCLDVTGIKQFLRFSTDKCILQQKQSMFIDVSLTTFGLTDAAVTRQVQGCYPLNVTAYYAYSEERSFVPNENVTVAFRINETSFYLPLPDTAYDVWICIKPPDGSVGETLGCNELDCTPRAVEPTTLIPSTVNPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVD',
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFGHQLLGGRYQVYGMKDCSGSGFANAERGTTFITEIIFENGVHISRGSYERAVKGIREIPLADGLLNPNRTRHDNVVSIQNDRIVAQYSMDNDTEIKGMEVWIEYVKINYCQPDPEHTIFWTVSTTKDLPPPGMATKVLAAFNIKNITGVSQKPMLVQRSVMRSEVVLTPNYKYSTELVNNTSTKVFVKVESVENVGVVRNDWYFGTVSHSIFTLYPNRAFFFDSVYKGGAPALVKPPTFKSLFSAGGLGYVDNMQYNVVVEKSKKCLPGDALSEVTACVFYLWQGDSFQQPHVSASRGKVTKERWSLVEKTCIFYQTTYKLLPVPSSLNATDEPALFQASFNPATKSIELCYKSPSIIGEGWPPLGSVTVAHKGETLMFGLVGSQPKGVYHERVAFESFPVTNNVPGLNVIAACVDDLLNYHSTSIHSFVKDQKVLNTKPPPETTLSTIEVYQINNNFNNTVYITFKFTLTTRTKVVNSSDAPYIDFKVMGEIHPHAVPNKSVSYPFSVFRT',
    ],
    sequences_with_fitness: [
      { fitness_score: 79.2, length: 571, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFDNPATYGNVSFGFWINVDHSTQKDDGVTFEIFPYSDDQLDAYTAQGTLSSLSLSFISSVDSHIVLEKQGLKVPGVVGLEIESFYWRFMFTVESQSSVDRYTLSFEKNPELFWEKWDTTLDRYMGQTGLSLGIPTIQSSLDCLDVTGIKQFLRFSTDKCILQQKQSMFIDVSLTTFGLTDAAVTRQVQGCYPLNVTAYYAYSEERSFVPNENVTVAFRINETSFYLPLPDTAYDVWICIKPPDGSVGETLGCNELDCTPRAVEPTTLIPSTVNPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVDPSTVD', repetition_warning: 'Tail dominated by 48x repetition of a 5-aa motif (240/512 aa). Likely a degenerate sample - regenerate or try a different model.' },
      { fitness_score: 53.5, length: 571, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFGHQLLGGRYQVYGMKDCSGSGFANAERGTTFITEIIFENGVHISRGSYERAVKGIREIPLADGLLNPNRTRHDNVVSIQNDRIVAQYSMDNDTEIKGMEVWIEYVKINYCQPDPEHTIFWTVSTTKDLPPPGMATKVLAAFNIKNITGVSQKPMLVQRSVMRSEVVLTPNYKYSTELVNNTSTKVFVKVESVENVGVVRNDWYFGTVSHSIFTLYPNRAFFFDSVYKGGAPALVKPPTFKSLFSAGGLGYVDNMQYNVVVEKSKKCLPGDALSEVTACVFYLWQGDSFQQPHVSASRGKVTKERWSLVEKTCIFYQTTYKLLPVPSSLNATDEPALFQASFNPATKSIELCYKSPSIIGEGWPPLGSVTVAHKGETLMFGLVGSQPKGVYHERVAFESFPVTNNVPGLNVIAACVDDLLNYHSTSIHSFVKDQKVLNTKPPPETTLSTIEVYQINNNFNNTVYITFKFTLTTRTKVVNSSDAPYIDFKVMGEIHPHAVPNKSVSYPFSVFRT' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 66.3, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-UR90', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- spike x 3b-GR-HM-c --
  '3b-GR-HM-c::MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFF': {
    success: true,
    sequences: [
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFLDFPHQPHLFHPLSRSKCPRFDQLKKMLDAMRQEQLPDGLTVVPSTPSLALQQTDMKSDGGASLAGSSIQDQAKMLLDPTSKNHFVAPQVLANVYDSSPFRSSNYVSKYPVNVEIPASSESGSSGRKSYSNAPRSFDQMKLSFGLPASRYVLPTTDVSRLLRGVQKDETSSVSYIAENHAILTSQTPRGWLNLAIVVLYLVVLLLGLAGNSLVIYVISKHRQMRTVTNFYIANLAATDVTFLLCCVPFTAVLYPLPGWIFGEFMCKFVAYMQQVTVQATCITLTAMSVDRWYVTVYPLRSLRQRTPRVALVVSLGIWVGSIVLCAPTFVFRDTMMDQDGHTTCSLNFFQQGWGGYKALLQQNTVALFFFTCFAPFVGFVGYASLYPPDAAGPVTETGSFLPLSSPNTSSSSSPPNLSGDPLPTSLTPADSNSTTSSSLVDSSDATNVGTATTSTTDNVTQPSSSLSASTLDPLEEAGLAAVMEFIPYPAILVLGLSGNCLVIFVMAQKKARR',
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFVPYLDPDSGNDGVYHQTLITGSRYDPEMQFPNNLRDYNNTVPTTPNRTLFVTERVPKYFTLIYFGYYECPDVCSTALSLLKRTKTMLTGLKAELKKARFLFVTLDPERDSPEVLSKYAKPIINEDKMHILTGSAQELRILQRQLNLYYRKEPNGDYYLIDTTGVYTAVIGKSPDTKRLLRVISKNLHSNILFFFTTLVLLLLIVFNLLIAALVEGVRDLENLEATIAISAQKRPQSSFDSIAHGRVIKRLVRATTGLAILVIVIVEIDVGGAPFSYSSLTSIQPGFQAIQWGLQLLRRSRSQRLAQLSSRLLSEGGSTTARTRSESVYQNKNTEWQDKLIKALPTYFPQVDRIFSDLGLEMWQQLDDTILNGIETVHPDGVRTSFRDYELPNMPLPTPPMRDDRGRTFSMGHRGEEGRSSSRTVRTVAMSEELHLSAYSTRLFFWLGLQLSVAMVLADLALLGLKPAQLVSGIISIVLSCAFLAEVFLVAKRRDQKIFLGRAFMVFVLNYIM',
    ],
    sequences_with_fitness: [
      { fitness_score: 68.5, length: 571, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFLDFPHQPHLFHPLSRSKCPRFDQLKKMLDAMRQEQLPDGLTVVPSTPSLALQQTDMKSDGGASLAGSSIQDQAKMLLDPTSKNHFVAPQVLANVYDSSPFRSSNYVSKYPVNVEIPASSESGSSGRKSYSNAPRSFDQMKLSFGLPASRYVLPTTDVSRLLRGVQKDETSSVSYIAENHAILTSQTPRGWLNLAIVVLYLVVLLLGLAGNSLVIYVISKHRQMRTVTNFYIANLAATDVTFLLCCVPFTAVLYPLPGWIFGEFMCKFVAYMQQVTVQATCITLTAMSVDRWYVTVYPLRSLRQRTPRVALVVSLGIWVGSIVLCAPTFVFRDTMMDQDGHTTCSLNFFQQGWGGYKALLQQNTVALFFFTCFAPFVGFVGYASLYPPDAAGPVTETGSFLPLSSPNTSSSSSPPNLSGDPLPTSLTPADSNSTTSSSLVDSSDATNVGTATTSTTDNVTQPSSSLSASTLDPLEEAGLAAVMEFIPYPAILVLGLSGNCLVIFVMAQKKARR' },
      { fitness_score: 57.0, length: 571, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFVPYLDPDSGNDGVYHQTLITGSRYDPEMQFPNNLRDYNNTVPTTPNRTLFVTERVPKYFTLIYFGYYECPDVCSTALSLLKRTKTMLTGLKAELKKARFLFVTLDPERDSPEVLSKYAKPIINEDKMHILTGSAQELRILQRQLNLYYRKEPNGDYYLIDTTGVYTAVIGKSPDTKRLLRVISKNLHSNILFFFTTLVLLLLIVFNLLIAALVEGVRDLENLEATIAISAQKRPQSSFDSIAHGRVIKRLVRATTGLAILVIVIVEIDVGGAPFSYSSLTSIQPGFQAIQWGLQLLRRSRSQRLAQLSSRLLSEGGSTTARTRSESVYQNKNTEWQDKLIKALPTYFPQVDRIFSDLGLEMWQQLDDTILNGIETVHPDGVRTSFRDYELPNMPLPTPPMRDDRGRTFSMGHRGEEGRSSSRTVRTVAMSEELHLSAYSTRLFFWLGLQLSVAMVLADLALLGLKPAQLVSGIISIVLSCAFLAEVFLVAKRRDQKIFLGRAFMVFVLNYIM' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 62.8, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 1, model: '3b-GR-HM-c', success_rate: 66.66666666666666, total_generated: 3, valid_count: 2 },
  },
  // -- spike x 3b-GR-HM --
  '3b-GR-HM::MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFF': {
    success: true,
    sequences: [
      'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFRSTFQRIRYFCLEKTRELGLSHPVYPFVVRHGRHADHGQKLPGPRPFYVGSSFMS',
    ],
    sequences_with_fitness: [
      { fitness_score: 53.2, length: 114, sequence: 'MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFRSTFQRIRYFCLEKTRELGLSHPVYPFVVRHGRHADHGQKLPGPRPFYVGSSFMS' },
    ],
    invalid_sequences: [],
    stats: { avg_fitness: 53.2, direction: 'n_to_c', generation_mode: 'unconditional', invalid_count: 2, model: '3b-GR-HM', success_rate: 33.33333333333333, total_generated: 3, valid_count: 1 },
  },
}
const CACHE_KEY = 'dayhoff-demo-cache'

/** Demo cache is keyed by both prompt and model so swapping models triggers a real run. */
function cacheKey(prompt: string, model?: string): string {
  return `${model ?? '170m-UR50-BRn'}::${prompt}`
}

export function getCachedResult(prompt: string, model?: string, _maxLength?: number, numSequences?: number): GenerationResponse | null {
  const key = cacheKey(prompt, model)
  const candidate: GenerationResponse | null =
    PRECOMPUTED[key] ??
    (() => {
      try {
        const raw = sessionStorage.getItem(CACHE_KEY)
        if (!raw) return null
        const cache = JSON.parse(raw) as Record<string, GenerationResponse>
        return cache[key] ?? null
      } catch {
        return null
      }
    })()

  if (!candidate) return null

  // Reject the cached entry only if it was generated with a different number of
  // candidates than the user is requesting. We DON'T compare lengths because
  // `maxLength` means "new residues to generate" while cached sequences include
  // the prompt — comparing total length against maxLength would always fail
  // (e.g. 56 aa Cas9 prompt + 512 generated = 568 aa total > maxLength 512).
  if (numSequences != null) {
    const cachedRequested = candidate.stats?.total_generated ?? candidate.sequences_with_fitness.length
    if (cachedRequested !== numSequences) return null
  }
  return candidate
}

export function setCachedResult(prompt: string, result: GenerationResponse, model?: string): void {
  try {
    const raw = sessionStorage.getItem(CACHE_KEY)
    const cache = raw ? JSON.parse(raw) : {}
    cache[cacheKey(prompt, model ?? result.stats?.model)] = result
    sessionStorage.setItem(CACHE_KEY, JSON.stringify(cache))
  } catch {
    // sessionStorage full or unavailable
  }
}
