"""
Protein Sequence Safety Screening for Dayhoff

Screens generated protein sequences against CDC/USDA Select Agent toxins.
Uses exact match + subsequence match + percent identity for variant detection.

Adapted from BioEmu's screening module. Key difference: BioEmu screens user
INPUT sequences; Dayhoff screens model OUTPUT sequences (generated proteins).

Sources:
- CDC/USDA Federal Select Agent Program (https://www.selectagents.gov/sat/list.htm)
- UniProt canonical sequences (https://www.uniprot.org/) — all entries verified
  via the UniProt REST API on 2026-03-24

Select Agent protein toxins covered:
  Abrin, Ricin, Botulinum neurotoxin (type A), Staphylococcal enterotoxin B,
  Shiga toxin (Stx1A + Stx2A + Stx2B), Epsilon toxin (C. perfringens),
  Conotoxin alpha-GI, Tetanus toxin, Diphtheria toxin.

Small-molecule Select Agent toxins (Saxitoxin, T-2 toxin, Tetrodotoxin,
Diacetoxyscirpenol) are not proteins and cannot be generated by Dayhoff.

To add entries:
  1. Find the UniProt accession for the toxin
  2. Fetch: https://rest.uniprot.org/uniprotkb/{ID}.fasta
  3. Add to TOXIN_SEQUENCES dict below with UniProt ID as comment
"""

from __future__ import annotations
import logging
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Select Agent Toxin Sequences (protein toxins only)
# ---------------------------------------------------------------------------
# Format: {"name": "SEQUENCE..."}
# ALL sequences are full-length canonical precursors from UniProt,
# uppercase, single-letter amino acid code.

TOXIN_SEQUENCES: dict[str, str] = {

    # ── Abrin (Select Agent) ──
    # Abrin-a, full precursor (UniProt P11140, 528 aa)
    "abrin_a": (
        "QDRPIKFSTEGATSQSYKQFIEALRERLRGGLIHDIPVLPDPTTLQERNRYITVELSNSDTES"
        "IEVGIDVTNAYVVAYRAGTQSYFLRDAPSSASDYLFTGTDQHSLPFYGTYGDLERWAHQSRQ"
        "QIPLGLQALTHGISFFRSGGNDNEEKARTLIVIIQMVAEAARFRYISNRVRVSIQTGTAFQPD"
        "AAMISLENNWDNLSRGVQESVQDTFPNQVTLTNIRNEPVIVDSLSHPTVAVLALMLFVCNPP"
        "NANQSPLLIRSIVEKSKICSSRYEPTVRIGGRDGMCVDVYDNGYHNGNRIIMWKCKDRLEEN"
        "QLWTLKSDKTIRSNGKCLTTYGYAPGSYVMIYDCTSAVAEATYWEIWDNGTIINPKSALVLSA"
        "ESSSMGGTLTVQTNEYLMRQGWRTGNNTSPFVTSISGYSDLCMQAQGSNVWMADCDSNKKEQ"
        "QWALYTDGSIRSVQNTNNCLTSKDHKQGSTILLMGCSNGWASQRWVFKNDGSIYSLYDDMVM"
        "DVKGSDPSLKQIILWPYTGKPNQIWLTLF"
    ),

    # ── Ricin (Select Agent) ──
    # Ricin, full precursor (UniProt P02879, 576 aa)
    "ricin": (
        "MKPGGNTIVIWMYAVATWLCFGSTSGWSFTLEDNNIFPKQYPIINFTTAGATVQSYTNFIRA"
        "VRGRLTTGADVRHEIPVLPNRVGLPINQRFILVELSNHAELSVTLALDVTNAYVVGYRAGNS"
        "AYFFHPDNQEDAEAITHLFTDVQNRYTFAFGGNYDRLEQLAGNLRENIELGNGPLEEAISALY"
        "YYSTGGTQLPTLARSFIICIQMISEAARFQYIEGEMRTRIRYNRRSAPDPSVITLENSWGRLS"
        "TAIQESNQGAFASPIQLQRRNGSKFSVYDVSILIPIIALMVYRCAPPPSSQFSLLIRPVVPNF"
        "NADVCMDPEPIVRIVGRNGLCVDVRDGRFHNGNAIQLWPCKSNTDANQLWTLKRDNTIRSNGK"
        "CLTTYGYSPGVYVMIYDCNTAATDATRWQIWDNGTIINPRSSLVLAATSGNSGTTLTVQTNIY"
        "AVSQGWLPTNNTQPFVTTIVGLYGLCLQANSGQVWIEDCSSEKAEQQWALYADGSIRPQQNR"
        "DNCLTSDSNIRETVVKILSCGPASSGQRWMFKNDGTILNLYSGLVLDVRASDPSLKQIILYPL"
        "HGDPNQIWLPLF"
    ),

    # ── Botulinum neurotoxin type A (Select Agent) ──
    # BoNT/A, full precursor (UniProt P0DPI0, 1296 aa)
    "botulinum_neurotoxin_a": (
        "MPFVNKQFNYKDPVNGVDIAYIKIPNVGQMQPVKAFKIHNKIWVIPERDTFTNPEEGDLNPP"
        "PEAKQVPVSYYDSTYLSTDNEKDNYLKGVTKLFERIYSTDLGRMLLTSIVRGIPFWGGSTIDT"
        "ELKVIDTNCINVIQPDGSYRSEELNLVIIGPSADIIQFECKSFGHEVLNLTRNGYGSTQYIRF"
        "SPDFTFGFEESLEVDTNPLLGAGKFATDPAVTLAHELIHAGHRLYGIAINPNRVFKVNTNAYYEM"
        "SGLEVSFEELRTFGGHDAKFIDSLQENEFRLYYYNKFKDIASTLNKAKSIVGTTASLQYMKNV"
        "FKEKYLLSEDTSGKFSVDKLKFDKLYKMLTEIYTEDNFVKFFKVLNRKTYLNFDKAVFKINI"
        "VPKVNYTIYDGFNLRNTNLAANFNGQNTEINNMNFTKLKNFTGLFEFYKLLCVRGIITSKTKS"
        "LDKGYNKALNDLCIKVNNWDLFFSPSEDNFTNDLNKGEEITSDTNIEAAEENISLDLIQQYYL"
        "TFNFDNEPENISIENLSSDIIGQLELMPNIERFPNGKKYELDKYTMFHYLRAQEFEHGKSRIA"
        "LTNSVNEALLNPSRVYTFFSSDYVKKVNKATEAAMFLGWVEQLVYDFTDETSEVSTTDKIADI"
        "TIIIPYIGPALNIGNMLYKDDFVGALIFSGAVILLEFIPEIAIPVLGTFALVSYIANKVLTVQT"
        "IDNALSKRNEKWDEVYKYIVTNWLAKVNTQIDLIRKKMKEALENQAEATKAIINYQYNQYTEE"
        "EKNNINFNIDDLSSKLNESINKAMININKFLNQCSVSYLMNSMIPYGVKRLEDFDASLKDALL"
        "KYIYDNRGTLIGQVDRLKDKVNNTLSTDIPFQLSKYVDNQRLLSTFTEYIKNIINTSILNLR"
        "YESNHLIDLSRYASKINIGSKVNFDPIDKNQIQLFNLESSKIEVILKNAIVYNSMYENFSTSFWI"
        "RIPKYFNSISLNNEYTIINCMENNSGWKVSLNYGEIIWTLQDTQEIKQRVVFKYSQMINISDY"
        "INRWIFVTITNNRLNNSKIYINGRLIDQKPISNLGNIHASNNIMFKLDGCRDTHRYIWIKYFN"
        "LFDKELNEKEIKDLYDNQSNSGILKDFWGDYLQYDKPYYMLNLYDPNKYVDVNNVGIRGYM"
        "YLKGPRGSVMTTNIYLNSSLYRGTKFIIKKYASGNKDNIVRNNDRVYINVVVKNKEYRLATN"
        "ASQAGVEKILSALEIPDVGNLSQVVVMKSKNDQGITNKCKMNLQDNNGNDIGFIGFHQFNNI"
        "AKLVASNWYNRQIERSSRTLGCSWEFIPVDDGWGERPL"
    ),

    # ── Staphylococcal enterotoxin B (Select Agent) ──
    # SEB, full precursor (UniProt P01552, 266 aa)
    "staph_enterotoxin_b": (
        "MYKRLFISHVILIFALILVISTPNVLAESQPDPKPDELHKSSKFTGLMENMKVLYDDNHVSAI"
        "NVKSIDQFLYFDLIYSIKDTKLGNYDNVRVEFKNKDLADKYKDKYVDVFGANYYYQCYFSKK"
        "TNDINSHQTDKRKTCMYGGVTEHNGNQLDKYRSITVRVFEDGKNLLSFDVQTNKKKVTAQEL"
        "DYLTRHYLVKNKKLYEFNNSPYETGYIKFIENENSFWYDMMPAPGDKFDQSKYLMMYNDNKMV"
        "DSKDVKIEVYLTTKKK"
    ),

    # ── Conotoxin alpha-GI (Select Agent) ──
    # Short paralytic peptide (13 aa, no UniProt — literature-verified)
    "conotoxin_alpha_gi": "ECCNPACGRHYSC",

    # ── Shiga toxin subunit A (Select Agent) ──
    # Stx1A from Shigella dysenteriae (UniProt Q9FBI2, 315 aa)
    "shiga_toxin_1a": (
        "MKIIIFRVLTFFFVIFSVNVVAKEFTLDFSTAKTYVDSLNVIRSAIGTPLQTISSGGTSLLMI"
        "DSGTGDNLFAVDVRGIDPEEGRFNNLRLIVERNNLYVTGFVNRTNNVFYRFADFSHVTFPGT"
        "TAVTLSGDSSYTTLQRVAGISRTGMQINRHSLTTSYLDLMSHSGTSLTQSVARAMLRFVTVT"
        "AEALRFRQIQRGFRTTLDDLSGRSYVMTAEDVDLTLNWGRLSSVLPDYHGQDSVRVGRISF"
        "GSINAILGSVALILNCHHHASRVARMASDEFPSMCPADGRVRGITHNKILWDSSTLGAILMRR"
        "TISS"
    ),

    # ── Shiga-like toxin 2 subunit A (Select Agent) ──
    # Stx2A from E. coli phage 933W (UniProt P09385, 319 aa)
    "shiga_toxin_2a": (
        "MKCILFKWVLCLLLGFSSVSYSREFTIDFSTQQSYVSSLNSIRTEISTPLEHISQGTTSVSVINHTP"
        "PGSYFAVDIRGLDVYQARFDHLRLIIEQNNLYVAGFVNTATNTFYRFSDFTHISVPGVTTVSM"
        "TTDSSYTTLQRVAALERSGMQISRHSLVSSYLALMEFSGNTMTRDASRAVLRFVTVTAEALRF"
        "RQIQREFRQALSETAPVYTMTPGDVDLTLNWGRISNVLPEYRGEDGVRVGRISFNNISAILG"
        "TVAVILNCHHQGARSVRAVNEESQPECQITGDRPVIKINNTLWESNTAAAFLNRKSQFLYTTGK"
    ),

    # ── Shiga-like toxin 2 subunit B (Select Agent) ──
    # Stx2B from E. coli phage 933W (UniProt P09386, 89 aa)
    "shiga_toxin_2b": (
        "MKKMFMAVLFALASVNAMAADCAKGKIEFSKYNEDDTFTVKVDGKEYWTSRWNLQPLLQSAQ"
        "LTGMTVTIKSSTCESGSGFAEVQFNND"
    ),

    # ── Epsilon toxin (Select Agent) ──
    # ETX type B, C. perfringens (UniProt Q02307, 328 aa)
    "epsilon_toxin": (
        "MKKNLVKSLAIASAVISIYSIVNIVSPTNVIAKEISNTVSNEMSKKASYDNVDTLIEKGRYNTK"
        "YNYLKRMEKYYPNAMAYFDKVTINPQGNDFYINNPKVELDGEPSMNYLEDVYVGKALLTNDTQ"
        "QEQKLKSQSFTCKNTDTVTATTTHTVGTSIQATAKFTVPFNETGVSLTTSYSFANTNTNTNSK"
        "EITHNVPSQDILVPANTTVEVIAYLKKVNVKGNVKLVGQVSGSEWGEIPSYLAFPRDGYKFSL"
        "SDTVNKSDLNEDGTININGKGNYSAVMGDELIVKVRNLNTNNVQEYVIPVDKKEKSNDSNIV"
        "KYRSLYIKAPGIK"
    ),

    # ── Tetanus toxin (Select Agent) ──
    # TeNT, full precursor (UniProt P04958, 1315 aa)
    "tetanus_toxin": (
        "MPITINNFRYSDPVNNDTIIMMEPPYCKGLDIYYKAFIITDRIWIVPERYEFGTKPEDFNPPS"
        "SLIEGASEYYDPNYLRTDSDKDRFLQTMVKLFNRIKNNVAGEALLDKIINAIPYLGNSYSLLD"
        "KFDTNSNSVSFNLLEQDPSGATTKSAMLTNLIIFGPGPVLNKNEVRGIVLRVDNKNYFPCRD"
        "GFGSIMQMAFCPEYVPTFDNVIENITSLTIGKSKYFQDPALLLMHELIHVLHGLYGMQVSSH"
        "EIIPSKQEIYMQHTYPISAEELFTFGGQDANLISIDIKNDLYEKTLNDYKAIANKLSQVTSCN"
        "DPNIDIDSYKQIYQQKYQFDKDSNGQYIVNEDKFQILYNSIMYGFTEIELGKKFNIKTRLSY"
        "FSMNHDPVKIPNLLDDTIYNDTEGFNIESKDLKSEYKGQNMRVNTNAFRNVDGSGLVSKLIG"
        "LCKKIIPPTNIRENLYNRTASLTDLGGELCIKIKNEDLTFIAEKNSFSEEPFQDEIVSYNTKNK"
        "PLNFNYSLDKIIVDYNLQSKITLPNDRTTPVTKGIPYAPEYKSNAASTIEIHNIDDNTIYQYL"
        "YAQKSPTTLQRITMTNSVDDALINSTKIYSYFPSVISKVNQGAQGILFLQWVRDIIDDFTNESSQ"
        "KTTIDKISDVSTIVPYIGPALNIVKQGYEGNFIGALETTGVVLLLEYIPEITLPVIAALSIA"
        "ESSTQKEKIIKTIDNFLEKRYEKWIEVYKLVKAKWLGTVNTQFQKRSYQMYRSLEYQVDAIKK"
        "IIDYEYKIYSGPDKEQIADEINNLKNKLEEKANKAMININIFMRESSRSFLVNQMINEAKKQL"
        "LEFDTQSKNILMQYIKANSKFIGITELKKLESKINKVFSTPIPFSYSKNLDCWVDNEEDIDVI"
        "LKKSTILNLDINNDIISDISGFNSSVITYPDAQLVPGINGKAIHLVNNESSEVIVHKAMDIEYN"
        "DMFNNFTVSFWLRVPKVSASHLEQYGTNEYSIISSMKKHSLSIGSGWSVSLKGNNLIWTLKDS"
        "AGEVRQITFRDLPDKFNAYLANKWVFITITNDRLSSANLYINGVLMGSAEITGLGAIREDNNI"
        "TLKLDRCNNNNQYVSIDKFRIFCKALNPKEIEKLYTSYLSITFLRDFWGNPLRYDTEYYLIPV"
        "ASSSKDVQLKNITDYMYLTNAPSYTNGKLNIYYRRLYNGLKFIIKRYTPNNEIDSFVKSGDFI"
        "KLYVSYNNNEHIVGYPKDGNAFNNLDRILRVGYNAPGIPLYKKMEAVKLRDLKTYSVQLKLYD"
        "DKNASLGLVGTHNGQIGNDPNRDILIASNWYFNHLKDKILGCDWYFVPTDEGWTND"
    ),

    # ── Diphtheria toxin (Select Agent) ──
    # DT, full precursor (UniProt P00588, 567 aa)
    "diphtheria_toxin": (
        "MLVRGYVVSRKLFASILIGALLGIGAPPSAHAGADDVVDSSKSFVMENFSSYHGTKPGYVDSI"
        "QKGIQKPKSGTQGNYDDDWKGFYSTDNKYDAAGYSVDNENPLSGKAGGVVKVTYPGLTKVL"
        "ALKVDNAETIKKELGLSLTEPLMEQVGTEEFIKRFGDGASRVVLSLPFAEGSSSVEYINNWE"
        "QAKALSVELEINFETRGKRGQDAMYEYMAQACAGNRVRRSVGSSLSCINLDWDVIRDKTKTKI"
        "ESLKEHGPIKNKMSESPNKTVSEEKAKQYLEEFHQTALEHPELSELKTVTGTNPVFAGANYA"
        "AWAVNVAQVIDSETADNLEKTTAALSILPGIGSVMGIADGAVHHNTEEIVAQSIALSSLMVAQ"
        "AIPLVGELVDIGFAAYNFVESIINLFQVVHNSYNRPAYSPGHKTQPFLHDGYAVSWNTVEDSI"
        "IRTGFQGESGHDIKITAENTPLPIAGVLLPTIPGKLDVNKSKTHISVNGRKIRMRCRAIDGD"
        "VTFCRPKSPVYVGNGVHANLHVAFHRSSSEKIHSNEISSDSIGVLGYQKTVDHTKVNSKLSL"
        "FFEIKS"
    ),
}

# Minimum percent identity to flag a sequence
SIMILARITY_THRESHOLD = 0.70  # 70% identity

# Minimum sequence length to screen (very short sequences match too broadly)
MIN_SCREEN_LENGTH = 13  # Shortest toxin is conotoxin at 13 aa


# ---------------------------------------------------------------------------
# Screening functions
# ---------------------------------------------------------------------------

def _percent_identity(seq1: str, seq2: str) -> float:
    """
    Simple percent identity between two sequences.
    Uses the shorter sequence as the reference length.
    Not a proper alignment — just a sliding window match.
    For production, use BLAST or MMseqs2.
    """
    seq1 = seq1.upper().strip()
    seq2 = seq2.upper().strip()

    if not seq1 or not seq2:
        return 0.0

    # If lengths are very different, skip expensive comparison
    shorter, longer = (seq1, seq2) if len(seq1) <= len(seq2) else (seq2, seq1)
    if len(shorter) / len(longer) < SIMILARITY_THRESHOLD:
        return 0.0

    # Simple ungapped alignment: count matching positions
    matches = sum(1 for a, b in zip(shorter, longer) if a == b)
    return matches / len(shorter)


def screen_sequence(sequence: str) -> Optional[str]:
    """
    Screen a protein sequence against Select Agent toxin database.

    Returns:
        None if the sequence is allowed.
        A string reason code if blocked (do NOT expose to user).
    """
    sequence = sequence.upper().strip()

    if not sequence or len(sequence) < MIN_SCREEN_LENGTH:
        return None

    for name, toxin_seq in TOXIN_SEQUENCES.items():
        toxin_upper = toxin_seq.upper()

        # Exact match
        if sequence == toxin_upper:
            return f"exact_match:{name}"

        # Subsequence match (generated sequence contains a full toxin,
        # or is a fragment of one)
        if sequence in toxin_upper or toxin_upper in sequence:
            return f"subsequence:{name}"

        # Percent identity match (variant detection)
        identity = _percent_identity(sequence, toxin_upper)
        if identity >= SIMILARITY_THRESHOLD:
            return f"similarity:{name}:{identity:.2f}"

    return None


def screen_generated_sequences(
    sequences_with_fitness: list[dict],
) -> tuple[list[dict], int]:
    """
    Screen a batch of generated sequences. Designed for Dayhoff's output
    filtering: removes flagged sequences silently from results.

    Args:
        sequences_with_fitness: list of dicts with at least a "sequence" key.

    Returns:
        (allowed_sequences, blocked_count) — filtered list and count of blocked.
    """
    allowed = []
    blocked_count = 0

    for entry in sequences_with_fitness:
        seq = entry.get("sequence", "")
        reason = screen_sequence(seq)
        if reason is not None:
            blocked_count += 1
            logger.warning(
                "SECURITY_BLOCK: endpoint=/api/generate type=output_filter "
                "reason=%s seq_len=%d",
                reason,
                len(seq),
            )
        else:
            allowed.append(entry)

    return allowed, blocked_count
